# Generated by Django 4.0 on 2022-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.IntegerField(choices=[(1, 'Classic Rock'), (2, 'Punk'), (3, 'Post Punk'), (4, 'Jazz'), (5, 'Hip Hop'), (6, 'Post Rock')])),
            ],
        ),
    ]
